# Generated by Django 3.1 on 2020-09-16 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200821_2305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
