# Generated by Django 3.1 on 2020-08-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dtp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.IntegerField(verbose_name='date')),
                ('Time', models.CharField(max_length=150, verbose_name='Time')),
                ('District', models.CharField(max_length=150, verbose_name='District')),
                ('DTP_V', models.CharField(max_length=150, verbose_name='DTP_V')),
                ('POG', models.IntegerField(verbose_name='POG')),
                ('RAN', models.IntegerField(verbose_name='RAN')),
                ('K_UCH', models.IntegerField(verbose_name='K_UCH')),
                ('n_p', models.CharField(max_length=150, verbose_name='n_p')),
                ('street', models.CharField(max_length=150, verbose_name='street')),
                ('house', models.IntegerField(verbose_name='house')),
                ('dor', models.CharField(max_length=150, verbose_name='dor')),
                ('factor', models.CharField(max_length=150, verbose_name='factor')),
                ('s_pog', models.CharField(max_length=150, verbose_name='s_pog')),
                ('s_pch', models.CharField(max_length=150, verbose_name='s_pch')),
                ('osv', models.CharField(max_length=150, verbose_name='osv')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longitude', models.FloatField(verbose_name='longitude')),
                ('OBJ_DTP', models.CharField(max_length=150, verbose_name='OBJ_DTP')),
                ('change_org_motion', models.CharField(max_length=150, verbose_name='change_org_motion')),
            ],
        ),
    ]
