# Generated by Django 3.1 on 2020-08-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtp',
            name='dor',
            field=models.CharField(max_length=150, null=True, verbose_name='dor'),
        ),
        migrations.AlterField(
            model_name='dtp',
            name='house',
            field=models.IntegerField(null=True, verbose_name='house'),
        ),
    ]
