# Generated by Django 3.1 on 2020-08-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statist', '0002_auto_20200821_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dtp',
            name='house',
            field=models.CharField(max_length=150, null=True, verbose_name='house'),
        ),
    ]
