# Generated by Django 3.1 on 2020-08-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DtpPoint2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.IntegerField(default=0, verbose_name='time')),
                ('latitude', models.FloatField(default=0, verbose_name='latitude')),
                ('longtitude', models.FloatField(default=0, verbose_name='longtitude')),
            ],
            options={
                'verbose_name': 'ДТП',
                'verbose_name_plural': 'ДТП',
            },
        ),
    ]
