# Generated by Django 3.1 on 2020-09-20 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DtpPoint2',
        ),
    ]
